### ISSUE TITLE
Early announcement of 1.6 changes

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1044]
If we know we are going to make some "breaking" changes (the quotes here are key, obviously we still want to retain backwards compatibility), we should try and announce + document these changes in advance.

We can use the 1.5.7 release to make people aware of these changes. This is a tentative list of changes in 1.6 that we should announce:

- [x] #295 Make callRemote return 0 as errno upon successful request (**note**: additional script warning should be added here in 1.5.7 too)
- [x] #1043 Make bad numberstrings error instead of warn
- [x] #1069 Make size (0,0) an error for browser creation functions
- [x] #1070 Changed Lua unsigned type check from warning to error
- [x] #1071 Remove deprecated mtalocal URL scheme

Obviously we will have more behavioural changes in 1.6 than we will announce alongside 1.5.7, but it's still helpful to give a heads up.

If you find more that needs to be put on this list, please feel free to edit this issue (or comment, if you are unable to edit). If this list ends up becoming too short we can of course just scrap this task altogether.

**Comment by qaisjp** [comment]
OK, I have documented (changelist and news post) both the callRemote callback change & the numberstrings change.

Is there anything else that we can announce ahead of time?

I am certain we should also pre-announce (and create 1.6 tickets for) these:

https://github.com/multitheftauto/mtasa-blue/blob/2336f780e6dcd250e2aecfe81fe9e5f95ca5d1d4/Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.cpp#L133

https://github.com/multitheftauto/mtasa-blue/blob/2336f780e6dcd250e2aecfe81fe9e5f95ca5d1d4/Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.cpp#L914

https://github.com/multitheftauto/mtasa-blue/blob/53121a3b3084b7e503d57be122f8649dd0bb09a8/Shared/sdk/CScriptArgReader.h#L72

https://github.com/multitheftauto/mtasa-blue/blob/2336f780e6dcd250e2aecfe81fe9e5f95ca5d1d4/Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.cpp#L267-L269

**Comment by qaisjp** [comment]
Unsigned integers by @Jusonex, Jan 2016: https://github.com/multitheftauto/mtasa-blue/commit/56e6a53f2c1a394cdceccce65efeb1f566c1eed0

Browser min size by @botder, Feb 2019: https://github.com/multitheftauto/mtasa-blue/commit/2336f780e6dcd250e2aecfe81fe9e5f95ca5d1d4

Deprecated url scheme by @Jusonex, August 2015: https://github.com/multitheftauto/mtasa-blue/commit/b8e2994b4395cd8e0654e62398387249bb0c0fdf

**Comment by qaisjp** [comment]
No response. I think I will go ahead with announcing the unsigned integers change but I will not do the others yet because:

- browser size change is too recent
- i am not sure about no longer supporting the deprecated url scheme

**Comment by jushar** [comment]
I think you can announce both changes - it won't matter if we really deprecate these functions or not.

**Comment by qaisjp** [comment]
Okay!

**Comment by qaisjp** [comment]
done

**Comment by dretax** [comment]
Jusonex is right, It seems absolutely fine.
