### ISSUE TITLE
Release 1.5.8

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1645]
This is a checklist of things to do, more or less [copied from the wiki](https://github.com/multitheftauto/mtasa-blue/wiki/Release-Checklist).

# Pre-Release

## Code

- [x] Ensure GitHub milestone is emptied, moving over to backlog accordingly
    - As of this comment (30th August) we only have one bug to fix left.
- [x] Revert volatile features/changes
    - [x] I don't think we need to revert anything?
- [x] [Make sure all new functions are added to CResourceChecker.Data.h](https://github.com/multitheftauto/mtasa-blue/wiki/Lua-API#how-to-add-a-new-lua-definition) (done in #1706)
- [x] Make sure `CCredits.cpp` is up to date (done in #1703)

## News post

- [x] Draft up news article, post on forum
    - @Lpsd has written and posted a great draft
- [x] Go through log (`git log 1.5.7...master`) and, on the changelog:
    - Note down nice new features
    - Note down nice bugfixes
    - Note down any community contributor (commit authors)
- [x] Go through list of features and do a once over for functionality tests
- [x] Ensure all new functions or changes have been documented on wiki.mtasa.com
- [x] Add highlights to the news post
- [x] Update your forum draft, asking for final feedback
- [x] Await approval of news post

Don't forget to include:

- [x] Resource contributors
    - [x] Lots of new work has been done on [AMX](https://github.com/multitheftauto/amx), so we should include a shout out to those that have worked on it (@colistro123, @AGraber, @Disinterpreter)
    - [x] Acknowledge the work on [mtasa-php-sdk](https://github.com/multitheftauto/mtasa-php-sdk) by @ecastro98 and encourage people to try it out

**Wiki**

- [x] If you encounter an already documented new feature, credit the authors of the wiki page
- [x] Update [Changes in 1.5.8](https://wiki.multitheftauto.com/wiki/Changes_in_1.5.8).

## MTA Client News

- [x] Create MTA client news (add files to `C:\ProgramData\MTA San Andreas All\1.5\news`, and use the `reloadnews` command ingame to refresh the list of news items and preview changes)
- [x] actually ship out news using ???? system

# Release

- [x] Bump version in code à la https://github.com/multitheftauto/mtasa-blue/commit/0017cec99b0c90ac1ee37d47f14798b010c5928a (Done in #1707)
- [x] Build new nightly
- [x] Start rolling out the update
    - [x] Bump the version number on the staff tools
        - [x] nightly
        - [x] full
        - [x] minclient
        - [x] release
    - [x] Tag mainline using `git tag 1.5.8 master` and push using `git push origin 1.5.8`
        - Side note: I wish we prefixed our tags with `v`.

## Social Media

- [x] Publish forum news post (it's okay if you're late by a little)
- [x] Announce on Discord (use @everyone and also publish to other guilds)
- [x] [Facebook](https://www.facebook.com/multitheftauto/)
- [x] [Twitter](https://twitter.com/mtaqa)
- [x] [ModDB](https://www.moddb.com/mods/multi-theft-auto-san-andreas)
- [x] [Steam](https://steamcommunity.com/groups/mta)
- [x] Create release on GitHub with link to the news post.
    - [x] Upload binaries

# Notes

There may be important things that I'm missing. Collaborators — please feel free to edit this issue with additional checkboxes.

**Feature freeze**

In #1377 we decided to experiment with a longer term feature freeze. Here are my reflections:

- I would recommend against doing _long_ feature freezes again. I think setting a date "we will release 1.5.8 on Friday" and then freezing for 1 week, as we did with the release of 1.5.7, would still be appropriate. This would primarily be for ensuring stability, instead of focusing on developing bugfixes.
- The original plan was that we freeze for 1.5 months and release later. But we didn't set a specific day for our deadline, and we're not great at deadlines altogether, so we just ended up not merging features for months.
- Expectation vs. Reality: the idea of working entirely on bug fixes sounds great, but in reality very few contributors like spending their time working on bug fixes.

**Comment by qaisjp** [comment]
We'll need to wait some more time to make sure #1641 and #1644 is stable.

**Comment by Woovie** [comment]
What is our state presently? :)

**Comment by qaisjp** [comment]
Just added #1667 to the milestone, which is a recently caused bug.

**Comment by Disinterpreter** [comment]
From the dialog about AMX:
![image](https://user-images.githubusercontent.com/3816155/94948259-b7a60780-04e7-11eb-82c9-6a8da036ce59.png)


I guess we should change @theSpool to @AGraber

**Comment by qaisjp** [comment]
Alright, most things are done now. Just a few checkboxes (bumping the `release` class and the client news).

**Comment by Woovie** [comment]
ready for close?
